TechShop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('register', register, name='register'),  # URL для реєстрації
    path('login', login_view, name='login'),      # URL для авторизації
    path('', home, name='home'),
    path('add-to-cart/<int:product_id>', add_to_cart, name='add_to_cart'),
    path('cart', show_cart, name='show_cart'),
    path('checkout', checkout, name='checkout'),
    path('order-success', order_success, name='order_success'),
    path('product/<int:product_id>', product_detail, name='product_detail'),
    path('logout', logout_view, name='logout'),  # URL для виходу користувача
]

main/models.py
from django.contrib.auth.models import User
from django.db import models


class Product(models.Model):
    brand = models.CharField(max_length=100, verbose_name='Бренд')
    name = models.CharField(max_length=200, verbose_name='Назва')
    specifications = models.TextField(verbose_name='Характеристики')
    description = models.TextField(verbose_name='Опис')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Ціна')
    img = models.CharField(max_length=350, verbose_name='Посилання на зображення')

    def __str__(self):
        return f"{self.brand} {self.name}"

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товари'


class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.product.name}"

    class Meta:
        verbose_name = 'Товар в кошику'
        verbose_name_plural = 'Товари в кошику'


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    full_name = models.CharField(max_length=100)
    address = models.TextField()

    def __str__(self):
        return f"Order {self.id} by {self.user.username}"

    class Meta:
        verbose_name = 'Замовлення'
        verbose_name_plural = 'Замовлення'

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return f"{self.quantity} of {self.product.name}"

    class Meta:
        verbose_name = 'Товар в замовленні'
        verbose_name_plural = 'Товари в замовленні'

main/forms.py
# forms.py
from django import forms
from .models import Product

class BrandFilterForm(forms.Form):
    brand_choices = [(brand, brand) for brand in Product.objects.order_by('brand').values_list('brand', flat=True).distinct()]
    brand = forms.ChoiceField(
        choices=[('', 'All makrs')] + brand_choices,
        required=False,
        label="Choose mark"
    )

main/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect, get_object_or_404

from main.forms import BrandFilterForm
from main.models import Product, CartItem, Order, OrderItem


def home(request):
    if not request.user.is_authenticated:
        return redirect('/login')  # Перенаправлення неавторизованих користувачів на сторінку логіну

    query = request.GET.get('q')  # Отримання пошукового запиту
    form = BrandFilterForm(request.GET or None)

    if form.is_valid() and form.cleaned_data.get('brand'):
        products = Product.objects.filter(brand=form.cleaned_data['brand'])
    elif query:
        products = Product.objects.filter(name__icontains=query)  # Пошук за назвою товару
    else:
        products = Product.objects.all()

    return render(request, 'home.html', {'products': products, 'form': form})

def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    cart_item, created = CartItem.objects.get_or_create(user=request.user, product=product)
    if not created:
        cart_item.quantity += 1  # збільшуємо кількість, якщо товар вже в кошику
    cart_item.save()
    return redirect('home')


# views.py

def checkout(request):
    cart_items = CartItem.objects.filter(user=request.user)
    if request.method == 'POST':
        full_name = request.POST.get('full_name')
        address = request.POST.get('address')

        if full_name and address:
            order = Order.objects.create(user=request.user, full_name=full_name, address=address)
            for item in cart_items:
                OrderItem.objects.create(order=order, product=item.product, quantity=item.quantity)
            cart_items.delete()  # Очищення кошика після оформлення замовлення
            return redirect('order_success')  # Перенаправлення на сторінку успішного оформлення замовлення
        # Тут можна додати повідомлення про помилку, якщо дані не введені

    return render(request, 'checkout.html', {'cart_items': cart_items})



def order_success(request):
    return render(request, 'order_success.html')



# views.py
def show_cart(request):
    cart_items = CartItem.objects.filter(user=request.user)
    for item in cart_items:
        item.total_price = item.quantity * item.product.price
    total_price = sum(item.product.price * item.quantity for item in cart_items)
    return render(request, 'cart.html', {'cart_items': cart_items, 'total_price':total_price})


def product_detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, 'product_detail.html', {'product': product})


# В'юшка для реєстрації
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')  # Перенаправлення на головну сторінку після реєстрації
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})

# В'юшка для авторизації
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home')  # Перенаправлення на головну сторінку після авторизації
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})  # Вірно вказаний шаблон авторизації


def logout_view(request):
    logout(request)
    return redirect('login')

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Electronics Store{% endblock %}</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
<style>
    .card-img-top {
        width: 100%; /* Ensures that the image takes up the full width of the card */
        height: 200px; /* Fixed image height */
        object-fit: contain; /* Ensures the image scales to fit completely */
        object-position: center; /* Centers the image */
    }
    .card {
        height: 100%; /* Ensures all cards in a row have the same height */
    }
</style>

</head>
<body>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Electronics Store</a>

        <form class="d-flex" method="get" action="{% url 'home' %}">
            <input class="form-control me-2" type="search" placeholder="Search products" aria-label="Search" name="q">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

        <div class="d-flex ms-auto">
            <a href="{% url 'show_cart' %}" class="nav-link">
                Cart
                <span class="badge badge-secondary">
                    {{ request.user.cartitem_set.count }}
                </span>
            </a>
            <a class="btn btn-outline-danger ms-3" href="/logout">Logout</a>
        </div>
    </div>
</nav>

    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}

{% block title %}Your Cart{% endblock %}

{% block content %}
    <div class="container">
        <h2>Cart</h2>
        {% if cart_items %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Price per unit</th>
                        <th>Total Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart_items %}
                        <tr>
                            <td>{{ item.product.name }}</td>
                            <td>{{ item.quantity }}</td>
                            <td>{{ item.product.price }} PLN</td>
                            <td>{{ item.total_price }} PLN</td>
                        </tr>
                    {% endfor %}
                        <tr>
                            <td> </td>
                            <td> </td>
                            <td> </td>
                            <td>{{total_price}} PLN</td>
                        </tr>
                </tbody>
            </table>
            <div class="text-right">
                <a href="{% url 'checkout' %}" class="btn btn-primary">Proceed to Checkout</a>
            </div>
        {% else %}
            <p>Your cart is empty.</p>
        {% endif %}
    </div>
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}

{% block title %}Checkout{% endblock %}

{% block content %}
    <div class="container mt-4">
        <h2>Checkout</h2>
        <form method="post" class="mt-3">
            {% csrf_token %}
            <div class="mb-3">
                <label for="full_name" class="form-label">Full Name:</label>
                <input type="text" class="form-control" id="full_name" name="full_name" required>
            </div>
            <div class="mb-3">
                <label for="address" class="form-label">Address:</label>
                <textarea class="form-control" id="address" name="address" rows="3" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Place Order</button>
        </form>
    </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
    <div class="container">
        <h2 class="mt-4">Product List</h2>
        <form method="get" class="mb-3">
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Filter</button>
        </form>
        <div class="row">
            {% for product in products %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <!-- Adding product image -->
                        {% if product.img %}
                            <img src="{{ product.img }}" class="card-img-top" alt="{{ product.name }}">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ product.brand }}</h6>
                            <p class="card-text">{{ product.description }}</p>
                            <p class="card-text"><small class="text-muted">{{ product.specifications }}</small></p>
                            <p class="card-text"><strong>Price:</strong> {{ product.price }} PLN</p>
                            <a href="{% url 'add_to_cart' product.id %}" class="btn btn-primary">Add to Cart</a>
                             <a href="{% url 'product_detail' product.id %}" class="btn btn-secondary">Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Authorization</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h2>Login Form</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
        <p>Don't have an account yet? <a href="/register">Register</a></p>
    </div>
</body>
</html>

templates/order_success.html
{% extends 'base.html' %}

{% block title %}Order Successfully Placed{% endblock %}

{% block content %}
    <div class="container mt-4">
        <h2 class="mb-3">Your Order Has Been Successfully Placed</h2>
        <p>Thank you for your order!</p>
    </div>
{% endblock %}

templates/product_detail.html
{% extends 'base.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <!-- Product textual information -->
            <div class="col-md-6">
                <h2>{{ product.name }}</h2>
                <p><strong>Brand:</strong> {{ product.brand }}</p>
                <p><strong>Description:</strong> {{ product.description }}</p>
                <p><strong>Price:</strong> {{ product.price }} PLN</p>
                <p><strong>Specifications:</strong></p>
                <pre>{{ product.specifications }}</pre>
                <a href="{% url 'add_to_cart' product.id %}" class="btn btn-primary mt-3">Add to Cart</a>
            </div>

            <!-- Column for product image -->
            <div class="col-md-6">
                {% if product.img %}
                    <img src="{{ product.img }}" alt="{{ product.name }}">
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Registration</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h2>Registration Form</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email" required>
            </div>
            <div class="form-group">
                <label for="password1">Password</label>
                <input type="password" class="form-control" id="password1" name="password1" required>
            </div>
            <div class="form-group">
                <label for="password2">Confirm Password</label>
                <input type="password" class="form-control" id="password2" name="password2" required>
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
         <p>Already have an account? <a href="/login">Login</a></p>
    </div>
</body>
</html>